# Generated by Django 6.0.3 on 2026-03-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_icon_emoji_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="content_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
